<div data-mage-init='{"hello": {"message": "HELLO WORLD!"}}'>
    Content
</div>
<button
        id="button1"
        title="<?php echo __('Open Modal') ?>">
        <?php echo __('Open Modal') ?>
</button>
<button
        id="button2"
        title="<?php echo __('Open Magento Login Model') ?>">
        <?php echo __('Open Magento Login Model') ?>
</button>
<button
        id="button3"
        title="<?php echo __('Open Custom Login Model') ?>">
        <?php echo __('Open Custom Login Model') ?>
</button>
<!--Popup login1-->
<!--<button type="button" class="action" data-trigger="trigger">
    <span data-bind="i18n: 'Click Here'"></span>
</button>
<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: $.mage.__('Submit'),
                class: 'action'
            }]
        }}">
    <div class="content">
        Popup Content
    </div>
</div>-->

