<?php
namespace Magenest\CategoryImport\Model\Import\Behavior;

class Basic extends \Magento\ImportExport\Model\Source\Import\AbstractBehavior
{
    public function toOptionArray()
    {
        return parent::toOptionArray(); // TODO: Change the autogenerated stub
    }


    public function getNotes($entityCode)
    {
        return parent::getNotes($entityCode); // TODO: Change the autogenerated stub
    }

    public function toArray()
    {
        return [];
    }

    public function getCode()
    {
        return 'basic';
    }
}