<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

    <p>
    <div class="field my_customer_image required">
        <label for="my_customer_image" class="label"><span><?php /* @escapeNotVerified */
                echo __('Image') ?></span></label>
        <div class="control">
            <input
                type="file" name="my_customer_image" id="my_customer_image"
                title="<?php /* @escapeNotVerified */
            echo __('Image') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>