<div data-mage-init='{"editcustomer": {}}'>
    <h2>Change Customer Information</h2>
    <input id="hidden_movie_id" type="hidden" value="<?php echo $block->getCustomerId();?>">
    FirstName:
    <input id="first-name-text" type="text" value="<?php echo $block->getFirstName();?>"/><br/>
    Last Name:
    <input id="last-name-text" type="text" value="<?php echo $block->getLastName();?>"/><br/>
    <button type="button" id="btn">Change Infor</button>
    <p id="notice"></p>
</div>