<div id="movie-div" data-bind="scope:'display'">
     <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#movie-div": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
           }
       }
   </script>

    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>

    <h2>Change Customer Information</h2>
    <input id="hidden_movie_id" type="hidden" value="<?php echo $block->getCustomerId();?>">
    First Name:
    <input data-bind="value: firstName" type="text"/>
    Last Name:
    <input data-bind="value: lastName" type="text"/>
    <button data-bind="click: changeInfor">Change Infor</button>
    <br/>
    <h2>Search Movie</h2>
    <input data-bind="value: searchMovieName, event: {change: getMovie}" id="text_search"  name="text_search" type="text"/>
    <button data-bind="click: getMovie">Search Movie</button>
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Movie Name</th>
            <th>Description</th>
            <th>Rating</th>
        </tr>
        </thead>
        <tbody data-bind="foreach: movieList">
        <tr>
            <td data-bind="text: movie_id"></td>
            <td>
                <!-- ko text: name--><!--/ko-->
            </td>
            <td data-bind="text: description"></td>
            <td data-bind="text: rating"></td>
        </tr>
        </tbody>
    </table>
</div>
